### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Chonghui-Liu** [labsyspharm/DRIAD#7]
Hello, I got an error "Error in value[[3L]](cond) : No credentials provided" when I ran the code" fnROSMAP <- wrangleROSMAP("~/test/ROSMAP") ".
 Please tell me how I should solve it.

**Comment by ArtemSokolov** [comment]
Hi @Chonghui-Liu,

Some things to check:
* Are you able to log into Synapse with `synapser::synLogin(rememberMe=TRUE)`?
* Do you have permissions to access ROSMAP data (https://www.synapse.org/#!Synapse:syn3219045)?

**Comment by Chonghui-Liu** [comment]
Thank you very much for your advice. @ArtemSokolov 

I've logged into synapse and have permissions to  access ROSMAP data. You can see that in the picture below.

![accepted](https://user-images.githubusercontent.com/38851783/218456862-cfa4fc4d-e153-4647-b08d-e551353bd0ed.png)
![error](https://user-images.githubusercontent.com/38851783/218456903-39c13016-e49b-47e8-8579-99dbfb79200a.png)

But I still couldn't download the data and get an error of "Error in value[[3L]](cond) : 
   This entity has access restrictions. Please visit the web page for this entity (syn.onweb("syn3505720")). Click the downward pointing arrow next to the file's name to review and fulfill its download requirement(s).".

**Comment by Chonghui-Liu** [comment]
I really want to learn the method of your paper "Machine learning identifies candidates for drug repurposing in Alzheimer’s disease", but it is too difficult to download the synpase data. Could you please send me an example data so that I can run and learn your code?

**Comment by ArtemSokolov** [comment]
Hi @Chonghui-Liu,

Can you please post the issue to https://www.synapse.org/#!Synapse:syn2580853/discussion/default? If you are able to download a file using your web browser, the programmatic Synapse client should really work, and it would be good to let Synapse developers know that there are issues with authentication. They can help work out where exactly things are going wrong.

In terms of learning the method, we are using basically the same approach (i.e., reduce the space of genes to a predefined set, then train a predictor of phenotype) in https://github.com/labsyspharm/brca-profiling That data is publicly available, so you should be able to run the code in that repository without needing to interface with Synapse.

-Artem

**Comment by Chonghui-Liu** [comment]
Hello, Dr. Artem Sokolov, 
Thank you very much for your patient guidance. I have learned the methods in the paper. I wish you success in your scientific research and hope to have the opportunity to learn from you.

**Comment by ArtemSokolov** [comment]
Thank you for the kind words, @Chonghui-Liu. I wish you all the best in your scientific career as well. I am going to close this issue, but please feel free to reopen if you have additional questions.
